2014/01/28 09:22:22 [error] [exception.CException] exception 'CException' with message 'UsersController and its behaviors do not have a method or closure named "sendJSON".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CComponent.php:266
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(78): CComponent->__call('sendJSON', Array)
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(78): UsersController->sendJSON(Array)
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(49): UsersController->actionCreate()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('create')
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/create')
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/server/users/create
HTTP_REFERER=http://social.loc/public/
---
2014/01/28 09:30:06 [warning] [application] Failed to set unsafe attribute "wait" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (74)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:36:10 [warning] [application] Failed to set unsafe attribute "silent" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (74)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:36:48 [warning] [application] Failed to set unsafe attribute "silent" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (74)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:39:00 [warning] [application] Failed to set unsafe attribute "silent" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (49)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:41:21 [warning] [application] Failed to set unsafe attribute "silent" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (49)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:41:32 [warning] [application] Failed to set unsafe attribute "silent" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (49)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:44:33 [warning] [application] Failed to set unsafe attribute "validate" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (49)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/01/29 08:45:26 [warning] [application] Failed to set unsafe attribute "validate" of "Users".
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (49)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/02/04 08:16:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "authenticate".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('authenticate')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('authenticate')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/authentic...')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/users/authenticate
HTTP_REFERER=http://social.loc/public/
---
2014/02/05 07:23:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "logout".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('logout')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('logout')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/logout')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/users/logout
HTTP_REFERER=http://social.loc/public/
---
2014/02/05 07:47:27 [error] [php] Trying to get property of non-object (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:109)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): UsersController->runActionWithFilters()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): UsersController->run()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/users/login
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (109)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/02/10 06:19:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "id".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('id')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('id')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/id')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/users/id/98
HTTP_REFERER=http://social.loc/public/
---
2014/02/11 07:27:15 [error] [php] Trying to get property of non-object (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:37)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): UsersController->runActionWithFilters()
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): UsersController->run()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/users/getuser/id/null
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (37)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/02/11 07:27:26 [error] [php] Trying to get property of non-object (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:37)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): UsersController->runActionWithFilters()
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): UsersController->run()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/users/getuser/id/null
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (37)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/02/13 07:13:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/13 07:20:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/13 07:57:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "search".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('search')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('search')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/search/va...')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/users/search/value/undefined
HTTP_REFERER=http://social.loc/public/
---
2014/02/13 08:15:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/13 08:29:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/17 08:45:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/17 08:46:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:24:32 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "session".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CComponent.php:266
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(58): CComponent->__call('session', Array)
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(58): CWebApplication->session('role')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(49): UsersController->actionGetrole()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('getrole')
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/getrole')
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/server/users/getrole
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:30:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:30:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:31:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:31:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "news/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/news/getall
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:36:28 [error] [php] Undefined variable: usersCollection (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\NewsController.php:15)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): NewsController->runAction()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): NewsController->runActionWithFilters()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): NewsController->run()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/news/getall
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\NewsController.php (15)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/02/19 08:41:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "search".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('search')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('search')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/search/val...')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/news/search/value/n
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:41:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "search".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('search')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('search')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/search/val...')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/news/search/value/ne
HTTP_REFERER=http://social.loc/public/
---
2014/02/19 08:41:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "search".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('search')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('search')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news/search/val...')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/news/search/value/new
HTTP_REFERER=http://social.loc/public/
---
2014/03/03 08:00:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(1458): CActiveRecord->getCommandBuilder()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(36): CActiveRecord->find('98')
#8 [internal function]: UsersController->actionGetuser('98')
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#15 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#16 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#17 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#18 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#19 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('getuser')
#20 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/getuser/i...')
#21 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#22 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#23 {main}
REQUEST_URI=/server/users/getuser/id/98
HTTP_REFERER=http://social.loc/public/
---
2014/03/04 07:21:44 [error] [php] Trying to get property of non-object (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:37)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): UsersController->runActionWithFilters()
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): UsersController->run()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/users/getuser/id/null
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (37)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/03/04 07:21:58 [error] [php] Trying to get property of non-object (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:37)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CAccessControlFilter->filter()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): UsersController->runActionWithFilters()
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): UsersController->run()
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/users/getuser/id/null
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php (37)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/03/06 08:21:33 [error] [exception.CException] exception 'CException' with message 'Property "Users.limit" is not defined.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CComponent.php:173
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(161): CComponent->__set('limit', '5')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(100): CActiveRecord->__set('limit', '5')
#2 [internal function]: UsersController->actionGetall('5')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('getall')
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/getall/li...')
#15 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/server/users/getall/limit/5
HTTP_REFERER=http://social.loc/public/
---
2014/03/19 07:18:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "undefined/getall/limit/5/offset/4".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('undefined/getal...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/undefined/getall/limit/5/offset/4
HTTP_REFERER=http://social.loc/public/
---
2014/03/19 07:19:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "undefined/getall/limit/5/offset/4".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('undefined/getal...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/undefined/getall/limit/5/offset/4
HTTP_REFERER=http://social.loc/public/
---
2014/03/31 07:55:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
HTTP_REFERER=http://social.loc/public/
---
2014/03/31 07:56:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/users/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/user...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/users/sadsajkhds
---
2014/03/31 07:56:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/model/users/data/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/mode...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/model/users/data/sadsajkhds
---
2014/03/31 07:57:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/model/users/data/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/mode...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/model/users/data/sadsajkhds
---
2014/03/31 07:57:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/model/users/data/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/mode...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/model/users/data/sadsajkhds
---
2014/03/31 07:57:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/model/users/data/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/mode...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/model/users/data/sadsajkhds
---
2014/03/31 07:57:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/model/users/data/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/mode...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/model/users/data/sadsajkhds
---
2014/03/31 07:57:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert/model/users/data/sadsajkhds".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert/mode...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert/model/users/data/sadsajkhds
---
2014/03/31 07:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
HTTP_REFERER=http://social.loc/public/
---
2014/03/31 07:58:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 07:58:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 07:59:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 07:59:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/
---
2014/03/31 07:59:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/
---
2014/03/31 07:59:52 [error] [exception.CException] exception 'CException' with message 'NewsController cannot find the requested view "index".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:878
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\NewsController.php(7): CController->render('index')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(49): NewsController->actionIndex()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('')
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('news')
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/server/news/
---
2014/03/31 08:00:09 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:336
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('view')
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/server/users/view
---
2014/03/31 08:00:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:231
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(30): UsersController->loadModel('1')
#1 [internal function]: UsersController->actionView('1')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('view')
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/server/users/view/1
---
2014/03/31 08:00:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:231
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(30): UsersController->loadModel('2')
#1 [internal function]: UsersController->actionView('2')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('view')
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/server/users/view/2
---
2014/03/31 08:00:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php:231
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\UsersController.php(30): UsersController->loadModel('3')
#1 [internal function]: UsersController->actionView('3')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(291): CFilterChain->run()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('view')
#13 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/server/users/view/3
---
2014/03/31 08:01:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api
---
2014/03/31 08:01:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 08:02:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 08:02:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 08:02:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 08:02:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
---
2014/03/31 08:04:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/index".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/index')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/index
---
2014/03/31 08:04:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/index".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/index')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/index
---
2014/03/31 08:04:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:04:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:04:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:07:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/index.php/api/get
---
2014/03/31 08:08:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/index".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/index')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/index
---
2014/03/31 08:08:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/index".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/index')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/index
---
2014/03/31 08:08:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/index".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/index')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/index
---
2014/03/31 08:08:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:08:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:08:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:08:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:08:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:08:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/get
---
2014/03/31 08:09:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "get".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:483
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(270): CController->missingAction('get')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('get')
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('users/get')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/server/users/get
---
2014/03/31 08:09:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/getall".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/getall')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/getall
---
2014/03/31 08:10:55 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:336
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert/mod...')
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/server/sapi/insert/mode/users
---
2014/03/31 08:11:05 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:336
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert/mod...')
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/server/sapi/insert/mode/users/data/fdgfd
---
2014/03/31 08:11:13 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:336
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert/mod...')
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/server/sapi/insert/mode/users/data/fdgfd
---
2014/03/31 08:11:14 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:336
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert/mod...')
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/server/sapi/insert/mode/users/data/fdgfd
---
2014/03/31 08:11:21 [error] [exception.CException] exception 'CException' with message 'CHttpRequest and its behaviors do not have a method or closure named "getPatam".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CComponent.php:266
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php(11): CComponent->__call('getPatam', Array)
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php(11): CHttpRequest->getPatam('data')
#2 [internal function]: SapiController->actionInsert('users', 'fdgfd')
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(SapiController), Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(SapiController), Object(ReflectionMethod), Array)
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert/mod...')
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/server/sapi/insert/model/users/data/fdgfd
---
2014/03/31 08:16:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api/insert".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('api/insert')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/server/api/insert
HTTP_REFERER=http://social.loc/public/
---
2014/03/31 08:16:42 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php:336
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert')
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/server/sapi/insert
HTTP_REFERER=http://social.loc/public/
---
2014/03/31 08:17:39 [error] [php] Missing argument 1 for CHttpRequest::getPost(), called in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php on line 8 and defined (D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CHttpRequest.php:197)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): SapiController->runAction()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): SapiController->runActionWithFilters()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): SapiController->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/sapi/insert
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php (8)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/03/31 08:22:11 [error] [php] json_decode() expects parameter 1 to be string, array given (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php:14)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): SapiController->runAction()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): SapiController->runActionWithFilters()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): SapiController->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/sapi/insert
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php (14)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/03/31 08:22:13 [error] [php] json_decode() expects parameter 1 to be string, array given (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php:14)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): SapiController->runAction()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): SapiController->runActionWithFilters()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): SapiController->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/sapi/insert
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php (14)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/03/31 08:27:13 [error] [exception.CDbException] exception 'CDbException' with message 'No columns are being updated for table "users".' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\schema\CDbCommandBuilder.php:392
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(1750): CDbCommandBuilder->createUpdateCommand(Object(CMysqlTableSchema), Array, Object(CDbCriteria))
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(1127): CActiveRecord->updateByPk(NULL, Array)
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php(807): CActiveRecord->update(Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php(16): CActiveRecord->save(false, Array)
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(49): SapiController->actionInsert()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#9 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert')
#10 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/server/sapi/insert
HTTP_REFERER=http://social.loc/public/
---
2014/03/31 08:30:09 [error] [exception.CDbException] exception 'CDbException' with message 'The active record cannot be inserted to database because it is not new.' in D:\EasyPHP\data\localweb\sicoal.loc\server\framework\db\ar\CActiveRecord.php:1073
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php(14): CActiveRecord->insert('{'email':'cc@cc...')
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\actions\CInlineAction.php(49): SapiController->actionInsert()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): CController->run('insert')
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController('sapi/insert')
#7 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/server/sapi/insert
---
2014/03/31 08:40:51 [error] [php] unserialize() [<a href='function.unserialize'>function.unserialize</a>]: Error at offset 0 of 21 bytes (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php:14)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): SapiController->runAction()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): SapiController->runActionWithFilters()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): SapiController->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/sapi/insert
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php (14)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
2014/03/31 08:47:57 [error] [php] json_decode() expects parameter 1 to be string, array given (D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php:14)
Stack trace:
#0 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(286): SapiController->runAction()
#2 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CController.php(265): SapiController->runActionWithFilters()
#3 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(282): SapiController->run()
#4 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\EasyPHP\data\localweb\sicoal.loc\server\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\EasyPHP\data\localweb\sicoal.loc\server\index.php(13): CWebApplication->run()
REQUEST_URI=/server/sapi/insert
in D:\EasyPHP\data\localweb\sicoal.loc\server\protected\controllers\SapiController.php (14)
in D:\EasyPHP\data\localweb\sicoal.loc\server\index.php (13)
